---
title: "College Grades"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Youtube Video
# https://www.youtube.com/watch?v=nx5yhXAQLxw

library(tidyverse)
library(ggplot2)
library(scales)
```



```{r}
recent_grads <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/college-majors/recent-grads.csv")
```

```{r}
recent_grads %>% View()
```



```{r}
#Histogram
recent_grads %>%
  ggplot(aes(Median)) +
  geom_histogram()
```

### What category of majors make more money

```{r}
recent_grads %>%
  mutate(Major_category = fct_reorder(Major_category, Median)) %>%
  ggplot(aes(Major_category, Median)) +
  geom_boxplot() +
  scale_y_continuous(labels = dollar_format()) +
  coord_flip()
```

```{r}
recent_grads %>%
  group_by(Major_category) %>%
  summarize(Median = median(Median)) %>%
  mutate(Major_category = fct_reorder(Major_category, Median)) %>%
  ggplot(aes(Major_category, Median)) +
  geom_col() +
  coord_flip()
```


### Whare are the highest earning majorS?

```{r}
  majors_processed <-recent_grads %>%
  arrange(desc(Median)) %>%
  select(Major, Major_category, Median, P25th, P75th) %>%
  mutate(Major = fct_reorder(Major, Median),
         Major = str_to_title(Major))
  majors_processed %>%
  head(20) %>%
  ggplot(aes(Major, Median, color= Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin=P25th, ymax=P75th)) +
  expand_limits(y=0) +
  scale_y_continuous(labels = dollar_format()) +
  coord_flip()

```

### What are the lowest earning majors

```{r}
  majors_processed %>%
  tail(20) %>%
  ggplot(aes(Major, Median, color= Major_category)) +
  geom_point() +
  geom_errorbar(aes(ymin=P25th, ymax=P75th)) +
  expand_limits(y=0) +
  scale_y_continuous(labels = dollar_format()) +
  coord_flip()
```




